"""
Regenerates INDEX.md by scanning all .sql files for their header blocks.

Usage:
    python _templates/generate_index.py

Assumes every .sql file follows the header format in query_template.sql:
    -- Title:            ...
    -- Vertical:         ...
    -- Author:           ...
    -- Last validated:   ...

Run this from the repo root. It overwrites INDEX.md, so hand-edits to
INDEX.md itself won't survive a regeneration — put durable notes in the
query header instead, not in the index.
"""

import re
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parent.parent
VERTICALS = ["marketing", "customer", "digital", "shared"]

FIELD_PATTERNS = {
    "title": re.compile(r"--\s*Title:\s*(.+)"),
    "vertical": re.compile(r"--\s*Vertical:\s*(.+)"),
    "author": re.compile(r"--\s*Author:\s*(.+)"),
    "last_validated": re.compile(r"--\s*Last validated:\s*(.+)"),
}


def parse_header(sql_text: str) -> dict:
    fields = {}
    for key, pattern in FIELD_PATTERNS.items():
        match = pattern.search(sql_text)
        fields[key] = match.group(1).strip() if match else ""
    return fields


def build_index() -> str:
    rows_by_vertical = defaultdict(list)

    for vertical in VERTICALS:
        vertical_dir = REPO_ROOT / vertical
        if not vertical_dir.exists():
            continue
        for sql_file in sorted(vertical_dir.rglob("*.sql")):
            text = sql_file.read_text(errors="ignore")
            fields = parse_header(text)
            rel_path = sql_file.relative_to(REPO_ROOT)
            rows_by_vertical[vertical.capitalize()].append(
                (str(rel_path), fields.get("title", ""), fields.get("author", ""),
                 fields.get("last_validated", ""))
            )

    lines = ["# Query Index\n",
              "Auto-generated by `_templates/generate_index.py`. Do not hand-edit — "
              "edit the header in the source .sql file and re-run the script instead.\n"]

    for vertical, rows in rows_by_vertical.items():
        lines.append(f"\n## {vertical}\n")
        lines.append("| File | Title | Owner | Last validated |")
        lines.append("|------|-------|-------|-----------------|")
        for file_path, title, author, last_validated in sorted(rows, key=lambda r: r[3], reverse=True):
            lines.append(f"| `{file_path}` | {title} | {author} | {last_validated} |")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    output = build_index()
    (REPO_ROOT / "INDEX.md").write_text(output)
    print(f"Wrote {REPO_ROOT / 'INDEX.md'}")
